### ISSUE TITLE
Error in arch container build

### ISSUE THREAD

**Issue by dbinary** [KSXGitHub/github-actions-deploy-aur#10]
Hi, today when run the github action I get the following error:

```bash 
Step 3/7 : RUN pacman -S --noconfirm --needed --overwrite '*'       openssh sudo       git fakeroot binutils gcc awk binutils xz       libarchive bzip2 coreutils file findutils       gettext grep gzip sed ncurses util-linux
   ---> Running in e7f53f4dd7e9
  error: failed to initialize alpm library
  (could not find or read directory: /var/lib/pacman/)
  The command '/bin/sh -c pacman -S --noconfirm --needed --overwrite '*'       openssh sudo       git fakeroot binutils gcc awk binutils xz       libarchive bzip2 coreutils file findutils       gettext grep gzip sed ncurses util-linux' returned a non-zero code: 255
```
![Screenshot_20210209_083616](https://user-images.githubusercontent.com/1562062/107378822-fa897480-6ab1-11eb-9e4d-961953cd6a09.png)

I found this [https://www.reddit.com/r/archlinux/comments/lek2ba/arch_linux_on_docker_ci_could_not_find_or_read/gmg4foj?utm_source=share&utm_medium=web2x&context=3](url) maybe help.

**Comment by KSXGitHub** [comment]
That reddit account (kredditacc96) is mine.

**Comment by KSXGitHub** [comment]
Can you try KSXGitHub/github-actions-deploy-aur@2b89cb6b44dbf7bd06916a1a2fe411357dfff236 and tell me the result?

**Comment by deimosfr** [comment]
Hi,

Having the same issue and tested your new image, now having:

```
Generating PKGBUILD and .SRCINFO
  Copying PKGBUILD...
  '/PKGBUILD' -> './PKGBUILD'
  Updating .SRCINFO
  ==> ERROR: /etc/makepkg.conf not found.
      Aborting...
```

Any idea?

Thanks

**Comment by KSXGitHub** [comment]
@deimosfr Can you try `72b5fe2a413d8f824fc12a2c5e4abba7229cd469`?

**Comment by deimosfr** [comment]
Not better :(

```
Run KSXGitHub/github-actions-deploy-aur@72b5fe2a413d8f824fc12a2c5e4abba7229cd469
...
Generating PKGBUILD and .SRCINFO
  Copying PKGBUILD...
  '/PKGBUILD' -> './PKGBUILD'
  Updating .SRCINFO
  ==> ERROR: /etc/makepkg.conf not found.
      Aborting...
```

**Comment by KSXGitHub** [comment]
Then I have no idea why it happens. If `/etc/makepkg.conf` does not exist, then the error should occur at `chmod` commands in `/entrypoint.sh`, not in `/build.sh`.

I will probably try invoking `docker` command directly at a later time.

**Comment by jbouter** [comment]
@KSXGitHub I've added a comment to your PR that might resolve the issue. I'm also experiencing the same currently with your GitHub Action.

**Comment by KSXGitHub** [comment]
I have patched glic-2.33 according to suggestion from [this reddit comment](https://www.reddit.com/r/archlinux/comments/lek2ba/arch_linux_on_docker_ci_could_not_find_or_read/gmziv8m?utm_source=share&utm_medium=web2x&context=3). Can you try `ef5cc6ec3fbd557ee95def420b2b422baeccbe6a`?

**Comment by deimosfr** [comment]
Still the same error:

```
Run KSXGitHub/github-actions-deploy-aur@ef5cc6ec3fbd557ee95def420b2b422baeccbe6a
...
Creating builder user
Initializing ssh directory
Copying PKGBUILD
Making sure that makepkg.conf is readable
Adding aur.archlinux.org to known hosts
Importing private key
Checksums of SSH keys
Configuring git
Cloning AUR package into /tmp/local-repo
Generating PKGBUILD and .SRCINFO
  Copying PKGBUILD...
  '/PKGBUILD' -> './PKGBUILD'
  Updating .SRCINFO
  ==> ERROR: /etc/makepkg.conf not found.
      Aborting...
```

**Comment by jbouter** [comment]
I have forked the content of this repository, and rebuilt it using `alpine` instead of `archlinux`. In case you're interested in the information, please see [jbouter/aur-releaser](https://github.com/jbouter/aur-releaser). It's a drop-in replacement for the current Workflow in case you wish to use it.

@KSXGitHub Feel free to use my work inside this repository. I have however released my custom additions under the GPL, rather than MIT license.

**Comment by michaeldwan** [comment]
We're also seeing the same issue on [superfly/flyctl](https://github.com/superfly/flyctl):

[using 2.2.3](https://github.com/superfly/flyctl/runs/1937388140?check_suite_focus=true#step:2:204)
[using ef5cc6ec3fbd557ee95def420b2b422baeccbe6a](https://github.com/superfly/flyctl/runs/1937573809?check_suite_focus=true#step:6:78)

Let me know if I can help debug this.

**Comment by KSXGitHub** [comment]
It seems GitHub has fixed Arch Linux related problems for us. Can you guys try again (with the latest tag this time)?

**Comment by deimosfr** [comment]
Hi,

I confirm with tag v2.2.3 it works \o/

Thanks for your time

**Comment by KSXGitHub** [comment]
If others confirm it as well I will close this issue.

**Comment by dbinary** [comment]
I also confirmed! Thanks
