### ISSUE TITLE
.SRCINFO publishing

### ISSUE THREAD

**Issue by andrii-bodnar** [KSXGitHub/github-actions-deploy-aur#12]
Hi, thanks for the great GH action!

I have a question regarding package version publishing.

Due to [AUR submission guidelines](https://wiki.archlinux.org/index.php/AUR_submission_guidelines), there is a requirement to update  `.SRCINFO` file along with `PKGBUILD`. 

> Be sure to regenerate .SRCINFO whenever PKGBUILD metadata changes, such as pkgver() updates; otherwise the AUR will not show updated version numbers.

But I don't see any options in this action allowing to publish the `.SRCINFO` also. How to deal with this requirement using this GH action?

**Comment by KSXGitHub** [comment]
It generates the `.SRCINFO` file from the `PKGBUILD` file.

**Comment by andrii-bodnar** [comment]
@KSXGitHub thanks for the answer!
