### ISSUE TITLE
Error SSHKEY

### ISSUE THREAD

**Issue by SquitchYT** [KSXGitHub/github-actions-deploy-aur#17]
Hello, i have an error during actions of your script :

Load key "/home/builder/.ssh/aur": invalid format
Importing private key
 mode of '/home/builder/.ssh/aur' changed from 0644 (rw-r--r--) to 0600 (rw-------)

after that, the actions is stoped

**Comment by KSXGitHub** [comment]
Lacking information. Closing.

**Comment by KSXGitHub** [comment]
Make sure both the private key you entered to GitHub secrets and the public key you entered to your AUR profile do not contain redundant newlines.
