### ISSUE TITLE
Automatically generate source sums

### ISSUE THREAD

**Issue by filips123** [KSXGitHub/github-actions-deploy-aur#19]
Can you add support for automatically adding source sums to `PKGBUILD`? I think this can be done by installing [`updpkgsums`](https://man.archlinux.org/man/community/pacman-contrib/updpkgsums.8.en) and then just running it before creating `.SRCINFO` in the `PKGBUILD` directory. This will automatically download all sources and put their sums into `PKGBUILD`.

**Comment by KSXGitHub** [comment]
Why don't you generate `PKGBUILD` with checksums or running `updpkgsums` yourself?

**Comment by filips123** [comment]
I think `updpkgsums` only works on Arch, so it is harder to use it on GH Actions without a custom Arch Docker image. So I think it would be easier to just add it to this action which already uses Arch.

I can probably create a PR that adds some option for this action to enable updating package sums.

**Comment by KSXGitHub** [comment]
> I think `updpkgsums` only works on Arch, so it is harder to use it on GH Actions without a custom Arch Docker image

Then create a custom Arch Docker GH Action. You can create a sub-directory in your repo and use it in your workflow file:

```yaml
- name: Run updpkgsums
  uses: ./path/to/custom-action/directory
```

**Comment by filips123** [comment]
Actually I found that I can use [Docker containers](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontainer) without creating new custom action, so it's easier than I thought.
