### ISSUE TITLE
Support pushing other files to AUR repository

### ISSUE THREAD

**Issue by filips123** [KSXGitHub/github-actions-deploy-aur#20]
I would like to publish other files (for example, `.gitignore`, `.install` script, patches, other assets...) to the AUR repository along with the `PKGBUILD` and `.SRCINFO`. I think this could be done by adding another input to the action (maybe `assets`) that accepts a list of files (maybe also whole directories or glob patterns), copies them to `/tmp/local-repo` and commits them along with existing files.

**Comment by KSXGitHub** [comment]
Let's just use `assets` key and glob pattern. However, I am busy right now, so I'll be accepting pull requests.
