### ISSUE TITLE
cp: missing file operand

### ISSUE THREAD

**Issue by j-waters** [KSXGitHub/github-actions-deploy-aur#22]
The action is no longer working for me, failing at the `Copying files into /tmp/local-repo` step:

```
Copying files into /tmp/local-repo
  Copying ./PKGBUILD
  Copying
  cp: missing file operand
  Try 'cp --help' for more information.
```

I believe it's because of this line https://github.com/KSXGitHub/github-actions-deploy-aur/blob/master/build.sh#L69 that was newly added

**Comment by KSXGitHub** [comment]
Can you try the new commit to see if there's still any problem?
