### ISSUE TITLE
invalid key format

### ISSUE THREAD

**Issue by ReenigneArcher** [KSXGitHub/github-actions-deploy-aur#27]
Same issue as #17 

https://github.com/SunshineStream/Sunshine/runs/6951924698?check_suite_focus=true#step:6:70
```txt
Importing private key
  mode of '/home/builder/.ssh/aur' changed from 0644 (rw-r--r--) to 0600 (rw-------)
  Load key "/home/builder/.ssh/aur": invalid format
```

**AUR account - SSH Public Key:**
```txt
ssh-rsa A...=
```
doesn't have any extra lines

**github secrets - AUR_SSH_PRIVATE_KEY**
```txt
b...
...
...
...
==
```
doesn't have any extra lines

I generated my key following these commands (https://phoenixnap.com/kb/generate-setup-ssh-key-ubuntu):
```bash
mkdir -p $HOME/.ssh
chmod 0700 $HOME/.ssh
ssh-keygen
```

public key came from `aur.pub` file
private key came from `aur` file

workflow step: https://github.com/SunshineStream/Sunshine/actions/runs/2522361975/workflow#L77

Maybe I did something wrong generating the key or adding it to my aur profile?

**Comment by KSXGitHub** [comment]
It is likely that you did something that corrupt your keys. I also personally experienced this issue before.

Make sure that the keys (after you paste it to GitHub secrets):
* Don't have trailing newline.
* Don't have leading newline.
* Use LF as line breaker, not CRLF.

**Comment by ReenigneArcher** [comment]
> It is likely that you did something that corrupt your keys. I also personally experienced this issue before.
> 
> Make sure that the keys (after you paste it to GitHub secrets):
> 
>     * Don't have trailing newline.
> 
>     * Don't have leading newline.
> 
>     * Use LF as line breaker, not CRLF.

Thanks for the reply... I meant to comment earlier, but I got this to work.

The issue was that I used a `passphrase` when generating my keys. I tried without and it worked. It would be a nice addition to support a `passphrase` if possible. Anyway, thanks!

**Comment by KSXGitHub** [comment]
`passphrase` is used to encrypt private keys, to prevent a malicious attacker from obtaining your private key even if they gain access to your computer, because even though they have access to your encrypted private key, they still don't know the passphrase you used to encrypt the key (because you didn't store the passphrase). To store `passphrase` in a GitHub secret would nullify its protection, rendering `passphrase` pointless.
