### ISSUE TITLE
no assets input?

### ISSUE THREAD

**Issue by pdobsan** [KSXGitHub/github-actions-deploy-aur#28]
According to the documentation there is an `assets` input, but when I use it I get the warning:

    Warning: Unexpected input(s) 'assets', valid inputs are ['entryPoint', 'args', 'pkgname', 'pkgbuild', 'commit_username', 'commit_email', 'ssh_private_key', 'commit_message', 'allow_empty_commits', 'force_push', 'ssh_keyscan_types']

In the following log however the input shows up:

    Run KSXGitHub/github-actions-deploy-aur@v2.2.5
      with:
        pkgname: mailctl-bin
        pkgbuild: ./aur/PKGBUILD
        assets: ./aur/.INSTALL

The end result was the update on assets (.INSTALL) never made it to the AUR repo.

**Comment by KSXGitHub** [comment]
It seems that I failed to review https://github.com/KSXGitHub/github-actions-deploy-aur/pull/21 properly. I will fix this when I get home.

**Comment by KSXGitHub** [comment]
Actually, it's not the PR's fault, it's just that the feature is not yet released. If you insist on using this feature, please use the latest commit in place of version tag (`github-actions-deploy-aur@beeaa2c21fccb825b1514089c02f260001c697bd`)

**Comment by ReenigneArcher** [comment]
@pdobsan please update us with your results if you use the unreleased version. I am interested in this as well, but haven't made a release yet in order to test.

**Comment by pdobsan** [comment]
Using the action with the suggested commit tag works as expected.

Actually this `assets` feature is important since many AUR packages are using `install` scripts potentially changing between releases.

**Comment by KSXGitHub** [comment]
v2.3.0 has been released.

**Comment by pdobsan** [comment]
> v2.3.0

Great, thank you!
