### ISSUE TITLE
src refspec master does not match any

### ISSUE THREAD

**Issue by ambition-echo** [KSXGitHub/github-actions-deploy-aur#30]
Hi

Help！I don't know why, I suddenly can't push to aur today

```
  add '.SRCINFO'
  add 'PKGBUILD'
  [detached HEAD 754f343] Update AUR package
   2 files changed, 2 insertions(+), 2 deletions(-)

  Pushing to ssh://aur.archlinux.org/earth-wallpaper-git.git
  error: src refspec master does not match any
  error: failed to push some refs to 'ssh://aur.archlinux.org/earth-wallpaper-git.git'
```

Is there any solution？

Thanks！

**Comment by KSXGitHub** [comment]
Can you point me to your repo? Not the AUR, but the GitHub repo that runs the action.

**Comment by ambition-echo** [comment]
[https://github.com/ambition-echo/earth_wallpaper](https://github.com/ambition-echo/earth_wallpaper)

This is the page where the problem occurs for the first time：
[https://github.com/ambition-echo/earth_wallpaper/actions/runs/2764574696](https://github.com/ambition-echo/earth_wallpaper/actions/runs/2764574696)

**Comment by KSXGitHub** [comment]
The problem is neither in my action nor your setup. It was that `-git` packages don't need and don't have branches. `-git` packages will always stay up-to-date to the latest commit without the author having to do anything. It seems that your effort in setting up a CI had been unnecessary.

**Comment by ambition-echo** [comment]
> The problem is neither in my action nor your setup. It was that `-git` packages don't need and don't have branches. `-git` packages will always stay up-to-date to the latest commit without the author having to do anything. It seems that your effort in setting up a CI had been unnecessary.

But all the actions before that are running without problems, I just want to update the version numbers of PKGBUILD, otherwise how can users receive software updates?I'm just new to aur.

**Comment by KSXGitHub** [comment]
> I just want to update the version numbers of PKGBUILD

I think the version number of a `-git` package is inconsequential. `makepkg` should always clone the latest commit.

If you really want to control the version number, I suggest creating a non-`git` package. For example: `earth-wallpaper-nightly` with version number `YYYY.MM.DD` (`YYYY` is year, `MM` is month, `DD` is day of month).

**Comment by ambition-echo** [comment]
>I suggest creating a non-`git` package. For example: `earth-wallpaper-nightly`

OK
Good idea!

Thank you for your patience, and good luck with your work!
