### ISSUE TITLE
aur@aur.archlinux.org: Permission denied (publickey)

### ISSUE THREAD

**Issue by FrenchGithubUser** [KSXGitHub/github-actions-deploy-aur#34]
I generated the ssh keys with `ssh-keygen` and ended up with 2 files, `aur` and `aur.pub`. I copied the content of `aur.pub` into my profile on the aur's website, and the content of `aur` into the github secrets. If I try to push from my local machine, no error happens, but from the github action, I get this output : 

```
  Getting AUR SSH Public keys
  # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.3
  # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.3
  # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.3
  # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.3
  # aur.archlinux.org:22 SSH-2.0-OpenSSH_9.3
  Writing SSH Private keys to file
  Setting up Git
  Cloning repo
  Cloning into 'hatt-bin'...
  Load key "/home/builder/.ssh/aur": error in libcrypto
  aur@aur.archlinux.org: Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
```

I'm not sure what I am doing wrong

**Comment by KSXGitHub** [comment]
Make sure to leave NO trailing newline in the github secret.

**Comment by FrenchGithubUser** [comment]
the issue is gone, thanks ! Idk how though...

but I now have this error : 
```
Copying ./PKGBUILD
  cp: cannot stat './PKGBUILD': No such file or directory
```

Is it taking the PKGBUILD file from the aur's git ?

**Comment by KSXGitHub** [comment]
You clearly didn't read the documentation of this github action. This action requires that you provide PKGBUILD in the github repo.
