### ISSUE TITLE
ERROR: Cannot find the debugedit binary required for including source files in debug packages

### ISSUE THREAD

**Issue by FunctionalHacker** [KSXGitHub/github-actions-deploy-aur#38]
Hi,

Thank you for the wonderful Action, it seems to work very well. Only thing I have a problem with is I cannot build the package because of this error

```
ERROR: Cannot find the debugedit binary required for including source files in debug packages.
```

You can see the error here https://github.com/FunctionalHacker/firefox-gnome-theme/actions/runs/8542900448/job/23405515025

**Comment by KSXGitHub** [comment]
Released [v2.7.1](https://github.com/KSXGitHub/github-actions-deploy-aur/releases/tag/v2.7.1)
