### ISSUE TITLE
failed to add aur.archlinux.org to known hosts Unknown key type "dsa"

### ISSUE THREAD

**Issue by doums** [KSXGitHub/github-actions-deploy-aur#39]
Hi, since recently (last week the action was still working fine), the action is failing

```
Adding aur.archlinux.org to known hosts` with the following error
  Unknown key type "dsa"
```

see https://github.com/nymtech/nym-vpn-client/actions/runs/9746853221/job/26898179272

**Comment by KSXGitHub** [comment]
It was probably disabled by Arch Linux itself

From https://wiki.archlinux.org/title/SSH_keys:

> OpenSSH 7.0 [deprecated and disabled support for DSA keys](https://archlinux.org/news/openssh-70p1-deprecates-ssh-dss-keys/) due to discovered vulnerabilities and OpenSSH 9.8 is built without support for DSA keys by default, therefore the choice of [cryptosystem](https://en.wikipedia.org/wiki/cryptosystem) lies within RSA or one of the two types of ECC.

**Comment by doums** [comment]
Sorry I'm not sure, does this mean that something needs to be fixed in the action side?

**Comment by KSXGitHub** [comment]
@doums I have removed `dsa` from default keyscan types. Let me know if it still error.

**Comment by doums** [comment]
Sorry I missed the `ssh_keyscan_types` input. But yea better to have valid defaults for it.
I confirm the new release of the action solves it https://github.com/nymtech/nym-vpn-client/actions/runs/9759650071/job/26936770343

Thanks!

**Comment by iTrooz** [comment]
You should probably remove the dsa key from the README example
