### ISSUE TITLE
Question: AUR "git" packages.

### ISSUE THREAD

**Issue by TheAlexDev23** [KSXGitHub/github-actions-deploy-aur#43]
It is common for AUR packages to have a separate version of the packages that ends with -git which downloads the latest commit instead of the latest release. 

Is it possible to create a workflow where both a release and a git package are published simultaneously with this action? I couldn't find any documentation regarding that.

**Comment by KSXGitHub** [comment]
You just need to run this action twice, one for each version.

**Comment by TheAlexDev23** [comment]
> You just need to run this action twice, one for each version.

Yeah figured it out later. I just misunderstood the instructions, I thought the action set missing values automatically, but I was supposed to generate the files from a script myself.

Now everything works like a charm, thank you for the action.
