### ISSUE TITLE
Source files

### ISSUE THREAD

**Issue by dbinary** [KSXGitHub/github-actions-deploy-aur#8]
When in the repository has source files in the root next to PKGBUILD, just the PKGBUILD is copied, and then makepkg fail.

![image](https://user-images.githubusercontent.com/1562062/94891513-840fa280-043f-11eb-8cd7-d2c1460cdd04.png)

**Comment by KSXGitHub** [comment]
Is your repo open source, I want to take a look.

**Comment by dbinary** [comment]
Yes, I could change to public. There is [ruby-mime](https://github.com/dbinary/ruby-mime)

**Comment by KSXGitHub** [comment]
@dbinary I have pushed my fix. Change the action to `KSXGitHub/github-actions-deploy-aur@e8d305d8e66a5444863f0a75eef9f2c7ecbd8915` to see if it works and tell me the test result. If it works, I will make an official release.

**Comment by dbinary** [comment]
Same error: `remote: error: missing source file: LICENSE`

![image](https://user-images.githubusercontent.com/1562062/94983429-fba50680-04ff-11eb-831d-efcc196b73d9.png)

**Comment by KSXGitHub** [comment]
This action only copies PKGBUILD. For source files, use URLs. Change [line 14 of your PKGBUILD](https://github.com/dbinary/ruby-mime/blob/e6a1b0167ddd88cecc392fb9b8a68add1b53cbd5/PKGBUILD#L14) to `https://github.com/dbinary/ruby-mime/raw/main/LICENSE`

**Comment by dbinary** [comment]
I understand, thank you

**Comment by KSXGitHub** [comment]
@dbinary BTW, use should never use master branch, use version tags instead, such as `KSXGitHub/github-actions-deploy-aur@v2.2.3`.

**Comment by dbinary** [comment]
OK thank you for advice, I'm going to change it.
